name: Docker Publish

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: registry.hvantoan.io.vn

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: registry.hvantoan.io.vn/hvantoan/T.Man:latest

      - name: SSH Remote Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: hvantoan.io.vn
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 24700
          script: |
            cd ctx/host-config/apps
            docker compose up --remove-orphans -d
